### ISSUE TITLE
Create About Us Component

### ISSUE THREAD

**Issue by skrpt** [feynman-project/homepage-mockup-v1#1]
- [ ] Write a brief intro about yourself, your career prospectives, passion, and why you're doing the Feynman Project

**Comment by hotpok3t** [comment]
@skrpt Where do we write this bio at?

**Comment by skrpt** [comment]
@hotpok3t create markdown file (md). Use this guide: 

-  https://help.github.com/categories/writing-on-github/
- http://daringfireball.net/projects/markdown/

**Comment by skrpt** [comment]
@PhilipWilburn I added you to this task. Let me know if you need help. Thanks.
